import { getEntries } from "./core/storage.js";
const KEY="sensoryLogManual_v1"; let entries=[], manual={notes:{}}, root=null;
const esc=v=>String(v??"").replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]));
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY)||"{}")}catch{return{}}}; const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(manual))}catch{}};
const top=(field,limit=3)=>{const m=new Map();entries.forEach(e=>(e[field]||[]).forEach(v=>m.set(v,(m.get(v)||0)+1)));return [...m.entries()].sort((a,b)=>b[1]-a[1]).slice(0,limit)};
function section(title,items,kind){return "<section class=\"sl-manual-section\"><div class=\"sl-manual-kicker\">"+kind+"</div><h3>"+title+"</h3>"+(items.length?items.map(x=>"<div class=\"sl-manual-item\"><span>"+esc(x[0])+"</span><small>"+x[1]+" logged day"+(x[1]===1?"":"s")+"</small></div>").join(""):"<p class=\"sl-manual-muted\">Nothing consistent enough to show yet.</p>")+"</section>"}
function build(){const energy=entries.filter(e=>e.energy>0).map(e=>e.energy),sensory=entries.filter(e=>e.overwhelm>0).map(e=>e.overwhelm),low=entries.filter(e=>e.energy>0&&e.energy<=2),high=entries.filter(e=>e.overwhelm>=4);return {signals:[["energy","Energy baseline",energy.length?"Your logged energy averages "+avg(energy).toFixed(1)+"/5 across "+energy.length+" days.":"Not enough logged days yet to estimate your baseline."],["sensory","Sensory load",sensory.length?"Your logged sensory load averages "+avg(sensory).toFixed(1)+"/5 across "+sensory.length+" days.":"Log a few more days to see your usual sensory load."],["low","Lower-capacity days",low.length?low.length+" logged days had energy at 1–2/5. Compare these with masking, sleep, social battery and drains.":"No lower-capacity days are recorded yet."],["high","High sensory-load days",high.length?high.length+" logged days had sensory load at 4–5/5.":"No high sensory-load days are recorded yet."]],supports:top("helped"),drains:top("drains"),body:top("body")}}
function render(){const d=build();root.innerHTML="<section class=\"sl-manual-hero\"><div><div class=\"sl-manual-kicker\">Personal operating manual</div><h2>Learn what your system tends to need.</h2><p>This is built from your own log. It describes patterns; it does not diagnose you.</p></div><span class=\"sl-manual-count\">"+entries.length+" days</span></section><section class=\"sl-manual-grid\">"+d.signals.map(s=>"<article class=\"sl-manual-card\"><div class=\"sl-manual-card-top\"><span>"+esc(s[1])+"</span><button type=\"button\" data-manual-note=\""+s[0]+"\">Edit</button></div><p>"+esc(s[2])+"</p>"+(manual.notes[s[0]]?"<blockquote>"+esc(manual.notes[s[0]])+"</blockquote>":"")+"<button class=\"sl-manual-note-btn\" type=\"button\" data-manual-note=\""+s[0]+"\">"+(manual.notes[s[0]]?"Change your note":"Add your own note")+"</button></article>").join("")+"</section>"+section("What has helped",d.supports,"Support")+section("Common drains",d.drains,"Load")+section("Body signals you log most",d.body,"Body")+"<section class=\"sl-manual-guidance\"><div class=\"sl-manual-kicker\">Use this as a guide</div><h3>Your manual can change.</h3><p>These observations become more useful as your history grows. A pattern is not a rule, and a difficult day is not a failure.</p><p>When you know something about yourself that the data cannot show yet, add it as your own note.</p></section>";bind()}
function bind(){root.querySelectorAll("[data-manual-note]").forEach(b=>b.onclick=()=>{const id=b.dataset.manualNote,value=prompt("What do you know about this part of your experience?",manual.notes[id]||"");if(value===null)return;manual.notes[id]=value.trim().slice(0,500);save();render()})}
export async function mountManual(){manual=load();entries=await getEntries();root=document.getElementById("slManual");if(!root){root=document.createElement("section");root.id="slManual";root.className="sl-manual";document.getElementById("slHistory")?.insertAdjacentElement("afterend",root)}render()}
mountManual();